<?php

namespace DoctrineORMModule\Proxy\__CG__\Chamado\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Chamado extends \Chamado\Entity\Chamado implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'id', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'titulo', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'descricao', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'protocolo', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'dtCriacao', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'dtFechamento', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'hrCriacao', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'idCliente', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'idStatusChamado', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'idUsuario', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'idResposta', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'idEmpresa', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'status');
        }

        return array('__isInitialized__', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'id', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'titulo', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'descricao', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'protocolo', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'dtCriacao', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'dtFechamento', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'hrCriacao', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'idCliente', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'idStatusChamado', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'idUsuario', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'idResposta', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'idEmpresa', '' . "\0" . 'Chamado\\Entity\\Chamado' . "\0" . 'status');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Chamado $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDtFechamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtFechamento', array());

        return parent::getDtFechamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtFechamento($dtFechamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtFechamento', array($dtFechamento));

        return parent::setDtFechamento($dtFechamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEmpresa(\Base\Entity\Empresa $idEmpresa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEmpresa', array($idEmpresa));

        return parent::setIdEmpresa($idEmpresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEmpresa', array());

        return parent::getIdEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdChamado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdChamado', array());

        return parent::getIdChamado();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', array($descricao));

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', array());

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setProtocolo($protocolo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProtocolo', array($protocolo));

        return parent::setProtocolo($protocolo);
    }

    /**
     * {@inheritDoc}
     */
    public function getProtocolo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProtocolo', array());

        return parent::getProtocolo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtCriacao', array());

        return parent::setDtCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getDtCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtCriacao', array());

        return parent::getDtCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrCriacao', array());

        return parent::setHrCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getHrCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrCriacao', array());

        return parent::getHrCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCliente(\Cliente\Entity\Cliente $idCliente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCliente', array($idCliente));

        return parent::setIdCliente($idCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCliente', array());

        return parent::getIdCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdStatusChamado(\Base\Entity\StatusChamado $idStatusChamado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdStatusChamado', array($idStatusChamado));

        return parent::setIdStatusChamado($idStatusChamado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdStatusChamado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdStatusChamado', array());

        return parent::getIdStatusChamado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario(\Usuario\Entity\Usuario $idUsuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdResposta(\Chamado\Entity\Chamado $idResposta = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdResposta', array($idResposta));

        return parent::setIdResposta($idResposta);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdResposta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdResposta', array());

        return parent::getIdResposta();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
