<?php

namespace DoctrineORMModule\Proxy\__CG__\evento\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evento extends \evento\Entity\Evento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'id', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'titulo', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'valorUni', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'dtCriacao', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'hrCriacao', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'dtIni', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'hrIni', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'dtFim', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'hrFim', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'observacao', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'status', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'repeticao');
        }

        return array('__isInitialized__', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'id', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'titulo', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'valorUni', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'dtCriacao', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'hrCriacao', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'dtIni', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'hrIni', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'dtFim', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'hrFim', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'observacao', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'status', '' . "\0" . 'evento\\Entity\\Evento' . "\0" . 'repeticao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdEvento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEvento', array());

        return parent::getIdEvento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorUni($valorUni)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorUni', array($valorUni));

        return parent::setValorUni($valorUni);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorUni()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorUni', array());

        return parent::getValorUni();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtCriacao($dtCriacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtCriacao', array($dtCriacao));

        return parent::setDtCriacao($dtCriacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtCriacao', array());

        return parent::getDtCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrCriacao($hrCriacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrCriacao', array($hrCriacao));

        return parent::setHrCriacao($hrCriacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrCriacao', array());

        return parent::getHrCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtIni($dtIni)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtIni', array($dtIni));

        return parent::setDtIni($dtIni);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtIni()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtIni', array());

        return parent::getDtIni();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrIni($hrIni)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrIni', array($hrIni));

        return parent::setHrIni($hrIni);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrIni()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrIni', array());

        return parent::getHrIni();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtFim($dtFim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtFim', array($dtFim));

        return parent::setDtFim($dtFim);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtFim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtFim', array());

        return parent::getDtFim();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrFim($hrFim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrFim', array($hrFim));

        return parent::setHrFim($hrFim);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrFim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrFim', array());

        return parent::getHrFim();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacao($observacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacao', array($observacao));

        return parent::setObservacao($observacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacao', array());

        return parent::getObservacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepeticao($repeticao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepeticao', array($repeticao));

        return parent::setRepeticao($repeticao);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepeticao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepeticao', array());

        return parent::getRepeticao();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
