<?php

namespace DoctrineORMModule\Proxy\__CG__\Oportunidade\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Oportunidade extends \Oportunidade\Entity\Oportunidade implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'id', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'dtAbertura', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'observacao', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'estimativa', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'dtCriacao', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'dtContato', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'hrCriacao', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idVendedor', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idCliente', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idSolucao', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idFornecedor', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idAgente', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idGestor', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idUsuario', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idStatusOportunidade', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idArea', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idEmpresa');
        }

        return array('__isInitialized__', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'id', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'dtAbertura', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'observacao', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'estimativa', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'dtCriacao', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'dtContato', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'hrCriacao', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idVendedor', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idCliente', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idSolucao', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idFornecedor', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idAgente', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idGestor', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idUsuario', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idStatusOportunidade', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idArea', '' . "\0" . 'Oportunidade\\Entity\\Oportunidade' . "\0" . 'idEmpresa');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Oportunidade $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDtContato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtContato', array());

        return parent::getDtContato();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtContato($dtContato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtContato', array($dtContato));

        return parent::setDtContato($dtContato);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEmpresa(\Base\Entity\Empresa $idEmpresa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEmpresa', array($idEmpresa));

        return parent::setIdEmpresa($idEmpresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEmpresa', array());

        return parent::getIdEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtCriacao', array());

        return parent::setDtCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getDtCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtCriacao', array());

        return parent::getDtCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdOportunidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOportunidade', array());

        return parent::getIdOportunidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtAbertura($dtAbertura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtAbertura', array($dtAbertura));

        return parent::setDtAbertura($dtAbertura);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtAbertura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtAbertura', array());

        return parent::getDtAbertura();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacao($observacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacao', array($observacao));

        return parent::setObservacao($observacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacao', array());

        return parent::getObservacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstimativa($estimativa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstimativa', array($estimativa));

        return parent::setEstimativa($estimativa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstimativa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstimativa', array());

        return parent::getEstimativa();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrCriacao', array());

        return parent::setHrCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getHrCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrCriacao', array());

        return parent::getHrCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdVendedor(\Base\Entity\Vendedor $idVendedor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdVendedor', array($idVendedor));

        return parent::setIdVendedor($idVendedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdVendedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdVendedor', array());

        return parent::getIdVendedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCliente(\Cliente\Entity\Cliente $idCliente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCliente', array($idCliente));

        return parent::setIdCliente($idCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCliente', array());

        return parent::getIdCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSolucao(\Base\Entity\Solucao $idSolucao = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSolucao', array($idSolucao));

        return parent::setIdSolucao($idSolucao);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSolucao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSolucao', array());

        return parent::getIdSolucao();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdFornecedor(\Base\Entity\Fornecedor $idFornecedor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdFornecedor', array($idFornecedor));

        return parent::setIdFornecedor($idFornecedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdFornecedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdFornecedor', array());

        return parent::getIdFornecedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAgente(\Base\Entity\Agente $idAgente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAgente', array($idAgente));

        return parent::setIdAgente($idAgente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAgente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAgente', array());

        return parent::getIdAgente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdGestor(\Base\Entity\Gestor $idGestor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdGestor', array($idGestor));

        return parent::setIdGestor($idGestor);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdGestor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdGestor', array());

        return parent::getIdGestor();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario(\Usuario\Entity\Usuario $idUsuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdStatusOportunidade(\Base\Entity\StatusOportunidade $idStatusOportunidade = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdStatusOportunidade', array($idStatusOportunidade));

        return parent::setIdStatusOportunidade($idStatusOportunidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdStatusOportunidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdStatusOportunidade', array());

        return parent::getIdStatusOportunidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdArea(\Base\Entity\Area $idArea = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdArea', array($idArea));

        return parent::setIdArea($idArea);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdArea', array());

        return parent::getIdArea();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
