<?php

namespace DoctrineORMModule\Proxy\__CG__\grupo\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Entrada extends \grupo\Entity\Entrada implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'id', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'dtCriacao', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'hrCriacao', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'tipo', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'observacao', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'valor', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'rotulo', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'qtd', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'idUsuario', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'idEvento');
        }

        return array('__isInitialized__', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'id', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'dtCriacao', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'hrCriacao', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'tipo', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'observacao', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'valor', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'rotulo', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'qtd', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'idUsuario', '' . "\0" . 'grupo\\Entity\\Entrada' . "\0" . 'idEvento');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Entrada $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdEntrada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEntrada', array());

        return parent::getIdEntrada();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtCriacao($dtCriacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtCriacao', array($dtCriacao));

        return parent::setDtCriacao($dtCriacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtCriacao', array());

        return parent::getDtCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrCriacao($hrCriacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrCriacao', array($hrCriacao));

        return parent::setHrCriacao($hrCriacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrCriacao', array());

        return parent::getHrCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacao($observacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacao', array($observacao));

        return parent::setObservacao($observacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacao', array());

        return parent::getObservacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setValor($valor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValor', array($valor));

        return parent::setValor($valor);
    }

    /**
     * {@inheritDoc}
     */
    public function getValor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValor', array());

        return parent::getValor();
    }

    /**
     * {@inheritDoc}
     */
    public function setRotulo($rotulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRotulo', array($rotulo));

        return parent::setRotulo($rotulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getRotulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRotulo', array());

        return parent::getRotulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtd($qtd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtd', array($qtd));

        return parent::setQtd($qtd);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtd', array());

        return parent::getQtd();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario(\usuario\Entity\Usuario $idUsuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEvento(\evento\Entity\Evento $idEvento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEvento', array($idEvento));

        return parent::setIdEvento($idEvento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEvento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEvento', array());

        return parent::getIdEvento();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
