<?php

namespace DoctrineORMModule\Proxy\__CG__\Produto\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produto extends \Produto\Entity\Produto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'id', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'descricao', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'dataValidade', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'dataCriacao', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'horaCriacao', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'custo', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'peso', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'quantidade', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'ultimaVenda', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'qtdMin', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'qtdMax');
        }

        return array('__isInitialized__', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'id', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'descricao', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'dataValidade', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'dataCriacao', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'horaCriacao', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'custo', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'peso', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'quantidade', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'ultimaVenda', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'qtdMin', '' . "\0" . 'Produto\\Entity\\Produto' . "\0" . 'qtdMax');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdProduto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProduto', array());

        return parent::getIdProduto();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', array($descricao));

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', array());

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataValidade($dataValidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataValidade', array($dataValidade));

        return parent::setDataValidade($dataValidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataValidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataValidade', array());

        return parent::getDataValidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCriacao', array());

        return parent::setDataCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCriacao', array());

        return parent::getDataCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraCriacao', array());

        return parent::setHoraCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraCriacao', array());

        return parent::getHoraCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCusto($custo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCusto', array($custo));

        return parent::setCusto($custo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCusto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCusto', array());

        return parent::getCusto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeso($peso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeso', array($peso));

        return parent::setPeso($peso);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeso', array());

        return parent::getPeso();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantidade($quantidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantidade', array($quantidade));

        return parent::setQuantidade($quantidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantidade', array());

        return parent::getQuantidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setUltimaVenda($ultimaVenda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUltimaVenda', array($ultimaVenda));

        return parent::setUltimaVenda($ultimaVenda);
    }

    /**
     * {@inheritDoc}
     */
    public function getUltimaVenda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUltimaVenda', array());

        return parent::getUltimaVenda();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtdMin($qtdMin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtdMin', array($qtdMin));

        return parent::setQtdMin($qtdMin);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtdMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtdMin', array());

        return parent::getQtdMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtdMax($qtdMax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtdMax', array($qtdMax));

        return parent::setQtdMax($qtdMax);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtdMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtdMax', array());

        return parent::getQtdMax();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
