<?php

namespace Base\Repository;

/**
 * AcoAcaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcoAcaoRepository extends \Doctrine\ORM\EntityRepository
{
}
