<?php

namespace Base\Repository;

/**
 * NtfNotificacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NtfNotificacaoRepository extends \Doctrine\ORM\EntityRepository
{
}
