<?php

namespace Base\Repository;

/**
 * OprOperacoesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OprOperacoesRepository extends \Doctrine\ORM\EntityRepository
{
}
