<?php

namespace Base\Repository;

/**
 * UsrUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsrUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
