

<div class="col-md-1">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Novo</button>
</div>

<div class="col-md-11" align="right" style="position: absolute;">
<?php
if($this->success)
    echo '<div align="left" class="alert alert-success alerta" style="margin-top: 0px"> '. $this->success[0] .' <button type="button" class="close" data-dismiss="alert"> x </button> </div>';
if($this->error)
    echo '<div align="left" class="alert alert-warning alerta" style="margin-top: 0px">'. $this->error[0] .' <button type="button" class="close" data-dismiss="alert"> x </button> </div>';
?>
</div>
<table class="table tabela table-striped table-hover table-condensed">
    <thead>
        <tr>
            <th>Nome </th>
            <th>E-mail </th>
            <th>Grupo </th>
            <th>Status </th>
            <th>Tipo </th>
            <th width="100px">Recursos </th>
        </tr>
    </thead>
    <tbody>
    <?php
    /**
     * @var $entity usuario\Entity\Usuario
     */
    ?>
    <?php if ($this->data): ?>
        <?php foreach($this->data as $entity){ ?>
        <tr>
            <td> <a href="#"><?php echo $entity->getNome(); ?> </a></td>
            <td> <a href="#"><?php echo $entity->getEmail(); ?> </a></td>
            <td> <a href="#"><?php if($entity->getIdGrupo()) echo $entity->getIdGrupo()->getNome(); ?> </a></td>
            <td> <a href="#"><?php echo $entity->getStatus(); ?> </a></td>
            <td> <a href="#"><?php if($entity->getIdTipoUsuario()) echo $entity->getIdTipoUsuario(); ?> </a></td>
            <td>
                <a class="btn-sm " href="<?php echo $this->url('usuario', array('controller' => 'usuario', 'action' => 'editar', 'id' => $entity->getIdUsuario() )); ?>"> <i class="glyphicon glyphicon-pencil"> </i> </a>
                <a class="btn-sm" href="<?php echo $this->url('usuario', array('controller' => 'usuario', 'action' => 'excluir', 'id' => $entity->getIdUsuario() )); ?>"> <i class="glyphicon glyphicon-trash"> </i> </a>
            </td>
        </tr>
        <?php } ?>
    <?php else: ?>
        <p> Nenhum registro encontrado! </p>
    <?php endif; ?>
    </tbody>
</table>

<!-- MODAL DE CADASTRO -->

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-usuario modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Cadastrar Usuário</h4>
            </div>

            <div class="formulario">
                <form id="form" method="post">
                    <div id="alerta"></div>
                    <div class="col-md-6">
                        <div class="form-group" id="f-nome">
                            <label for="recipient-name" class="control-label">Nome:</label>
                            <input type="text" class="form-control" id="nome" name="nome">
                        </div>
                        <div class="form-group" id="f-email">
                            <label for="recipient-name" class="control-label">E-Mail:</label>
                            <input type="email" class="form-control" id="email" name="email">
                        </div>
                        <div class="form-group" id="f-grupo">
                            <label for="recipient-name" class="control-label">Grupo:</label>
                            <select class="form-control" id="id_grupo" name="id_grupo">
                                <option value=""> ::Selecione:: </option>
                                <?php
                                /**
                                 * @var $entity grupo\Entity\Grupo
                                 */
                                ?>
                                <?php if($this->grupo){ ?>
                                <?php foreach($this->grupo as $entity){ ?>
                                    <option value="<?php echo $entity->getIdGrupo(); ?>"> <?php echo $entity->getNome(); ?> </option>
                                <?php }} ?>
                            </select>
                        </div>
                    </div> <!-- fim col-md-6 -->

                    <div class="col-md-6">
                        <div class="form-group" id="f-senha">
                            <label for="recipient-name" class="control-label">Senha:</label>
                            <input type="password" class="form-control" id="senha" name="senha">
                        </div>
                        <div class="form-group" id="f-senha-2">
                            <label for="recipient-name" class="control-label">Repita a Senha:</label>
                            <input type="password" class="form-control" id="senha_2" name="senha_2">
                        </div>
                    </div> <!-- fim col-md-6 -->

                    <div  class="form-group" align="right">
                        <a class="btn btn-success btn-md btn-right" data-loading-text="Carregando..." id="btn-submit-usuario">Salvar</a>
                    </div>

                </form>
            </div>

        </div>
    </div>
</div>

<script>
    $("#li-eventos, #li-sisters, #li-entradas, #li-despesas, #li-grupos ").removeClass("active");
    //$("#li-grupos").addClass("active");
</script>