<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/paginas.css')
                        ->prependStylesheet($this->basePath() . '/css/login.css')
                        ->prependStylesheet($this->basePath() . '/css/navbar.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/paginas.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/jquery.js')
            ->prependFile($this->basePath() . '/js/jquery.tokeninput.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>

    <?php //if($this->identity()[0]){  ?>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Sistema em Zend') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right ">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle"  data-toggle="dropdown">Usuário<?php //echo $this->identity()[0]->getNome(); ?> <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu2">
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Meu perfil</a></li>
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Sair</a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="col-md-2">

            <div class="nav-side-menu">

                <div class="menu-list">

                    <ul id="menu-content" class="menu-content collapse out">

                        <li id="li-eventos" class="active">
                            <a href="<?php echo $this->url('Base', array('controller' => 'Base', 'action' => 'acoes')); ?>">
                                <i class="fa fa-users fa-lg"></i> Ações
                            </a>
                        </li>

                        <li id="li-sisters">
                            <a href="#">
                                <i class="fa fa-users fa-lg"></i> Notificações
                            </a>
                        </li>
                        <li id="li-grupos">
                            <a href="#">
                                <i class="fa fa-users fa-lg"></i> Usuários
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>



        <div class="container col-md-10">
            <div class="container-dentro">
                <?php echo $this->content; ?>
            </div>
            <hr>
        </div> <!-- /container -->
        <?php /*?>
        <footer class="rodape">
            <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
        </footer>
        <?php */?>
        <?php echo $this->inlineScript() ?>



    <style>
        .container-dentro{
            margin-top: 38px;
        }
    </style>
    </body>
</html>
