


<?php
/**
 *
 * @var $form \Zend\Form\Form
 */
$form= $this->form;


if($this->success)
    echo '<div class="alert alert-success"> '. $this->success[0] .' <button type="button" class="close" data-dismiss="alert"> x </button> </div>';
if($this->error)
    echo '<div class="alert alert-warning">'. $this->error[0] .' <button type="button" class="close" data-dismiss="alert"> x </button> </div>';

$this->formElementErrors()
    ->setMessageOpenFormat ('<div class="alert alert-danger"> <button type="button" class="close" data-dismiss="alert"> x </button>')
    ->setMessageCloseString ('</div>');
    //->render ($form);

//$form->setAttribute('action', $this->url('Base', array('controller' => 'Base', 'action' => 'acoes')));

//$form->prepare();


/*
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
*/
?>

<h3>Ações</h3>
<form method="post" >
    <label>Tipo</label>
    <select name="OPR_TIPO_OPERACAO">
        <option value="compra"> Compra</option>
        <option value="venda"> Venda</option>
    </select>

    <label>Data</label>
    <input type="date" name="OPR_DATA_OPERACAO">

    <label>Ação</label>
    <select name="OPR_ACAO">
        <option value="0"> --Selecione-- </option>
        <?php if($this->acao){ ?>
        <?php foreach($this->acao as $acao){ ?>
            <option value="<?php if($acao->getAcoIdAcao()) echo $acao->getAcoIdAcao(); ?>"> <?php if($acao->getAcoNomeAcao()) echo $acao->getAcoNomeAcao(); ?> </option>

        <?php } } ?>
    </select>
    <label>Quantidade</label>
    <input type="text" name="OPR_QTD">
    <label>Preço</label>
    <input type="text" name="OPR_VALOR">
    <label>Corretagem</label>
    <input type="text" name="OPR_CORRETAGEM">

    <br>
    <input type="submit" value="Cadastrar">
</form>

<style type="text/css">
    input, textarea, label{
        display: block;
    }
</style>