<div class="">
    <h2>Lista de Ações</h2>

    <div class="col-md-8">
        <label>Filtro</label>
        <input type="text">
        <input type="text">
        <select>
            <option value="0"> --Selecione-- </option>
        </select>
    </div>
    <div class="col-md-4">
        <span>Saldo em Ações: </span>
        <span>Valor captal: </span>
        <span>Rentabilidade: </span>

    </div>
    <div class="tab_aco">
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <td>Cod.</td>
                    <td>Cotação atual</td>
                    <td>Max dia</td>
                    <td>Min dia</td>
                    <td>Fechamento anterior</td>
                    <td>Variação</td>
                    <td>Operações</td>
                </tr>
            </thead>

            <tbody>
            <?php if($this->data){ ?>
            <?php foreach($this->data as $data){ ?>
                    <tr>
                        <td><?php echo $data->getAcoCodigoAcao(); ?></td>
                        <td><?php echo $data->getAcoValorAtual(); ?></td>
                        <td><?php echo $data->getAcoValorMaximo(); ?></td>
                        <td><?php echo $data->getAcoValorMinimo(); ?></td>
                        <td><?php echo ""; ?></td>
                        <td><?php echo ""; ?></td>
                        <td></td>
                    </tr>
            <?php } } ?>
            </tbody>
        </table>
    </div>
</div>

<style>
    .tab_aco{
        margin: 80px 0 0 0;
    }
    span, label{
        display: block;
    }
</style>

