

<div align="left">
    Você esta em: <a href="<?php echo $this->url('Usuario', array('controller' => 'Usuario', 'action' => 'index')); ?>">Usuario </a>  > <u>Editar <?php echo $this->data['nome'] ?></u>
</div>
<br>


<div class="tabela col-md-12">
    <div class="tabela-dentro" align="left">
        <h3 class="texto" style="font-size: 18px"> Cadastrar Usuário </h3>
        <?php
        if($this->success)
            echo '<div class="alert alert-success"> '. $this->success[0] .' <button type="button" class="close" data-dismiss="alert"> x </button> </div>';
        if($this->error)
            echo '<div class="alert alert-warning">'. $this->error[0] .' <button type="button" class="close" data-dismiss="alert"> x </button> </div>';

        $this->formElementErrors()
            ->setMessageOpenFormat ('<div class="alert alert-danger"> <button type="button" class="close" data-dismiss="alert"> x </button>')
            ->setMessageCloseString ('</div>');

        ?>

        <form class="" method="post" action="">
            <div class="col-md-4">
                <div class="form-group">
                    <label >Tipo</label>
                    <input type="text" class="form-control" name="tipo"  placeholder="" value="<?php echo $this->data['tipo'] ?>" disabled>
                </div>

                <?php //if( $this->data['tipo'] == 'cliente'){ ?>
                <div class="form-group">
                    <label >Nome</label>
                    <input type="text" class="form-control" name="nome"  placeholder="" value="<?php echo $this->data['nome'] ?>">
                </div>

                <div  class="form-group">
                    <label >E-mail</label>
                    <input type="email" class="form-control" name="email"  placeholder="" value="<?php echo $this->data['email'] ?>">
                </div>

                <div  class="form-group">
                    <label >Ativo</label>
                    <input type="checkbox" <?php if( $this->data['ativo'] == 1) echo 'checked="yes"' ; ?> value="1" name="ativo"  placeholder="">
                </div>

                <label>Permissões</label>
                <div id="permissoes">
                    <table class="table table-striped table-condensed table-bordered">
                        <thead>
                        <tr>
                            <td></td>
                            <td>Cliente</td>
                            <td>Equipamento</td>
                            <td>Contato</td>
                            <td>Arquivos</td>
                            <td>Oportunidade</td>
                            <td>Eventos</td>
                            <td>Chamados</td>
                            <td>Status Chamado</td>
                            <td>Outros Cadastros</td>
                            <td>Empresas</td>
                            <td>Usuarios</td>
                        </tr>
                        </thead>
                        <tbody align="center">
                        <tr>
                            <td>Cadastrar</td>
                            <td><input <?php if( $this->data['id_permissao']->getInCl() == 1) echo 'checked="yes"' ; ?>  name="in_cl" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getInEq() == 1) echo 'checked="yes"' ; ?>  name="in_eq" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getInCo() == 1) echo 'checked="yes"' ; ?>  name="in_co" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getInAr() == 1) echo 'checked="yes"' ; ?>  name="in_ar" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getInOp() == 1) echo 'checked="yes"' ; ?>  name="in_op" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getInEv() == 1) echo 'checked="yes"' ; ?>  name="in_ev" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getInCh() == 1) echo 'checked="yes"' ; ?>  name="in_ch" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getInSt() == 1) echo 'checked="yes"' ; ?>  name="in_st" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getInOu() == 1) echo 'checked="yes"' ; ?>  name="in_ou" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getInEm() == 1) echo 'checked="yes"' ; ?>  name="in_em" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getInUs() == 1) echo 'checked="yes"' ; ?>  name="in_us" value="1" type="checkbox"></td>
                        </tr>
                        <tr>
                            <td>Visualizar</td>
                            <td><input name="vi_cl" value="1" <?php if( $this->data['id_permissao']->getViCl() == 1) echo 'checked="yes"' ; ?>  type="checkbox"></td>
                            <td><input  <?php if( $this->data['id_permissao']->getViEq() == 1) echo 'checked="yes"' ; ?> name="vi_eq" value="1" type="checkbox"></td>
                            <td><input  <?php if( $this->data['id_permissao']->getViCo() == 1) echo 'checked="yes"' ; ?> name="vi_co" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getViAr() == 1) echo 'checked="yes"' ; ?>  name="vi_ar" value="1" type="checkbox"></td>
                            <td><input  <?php if( $this->data['id_permissao']->getViOp() == 1) echo 'checked="yes"' ; ?> name="vi_op" value="1" type="checkbox"></td>
                            <td><input  <?php if( $this->data['id_permissao']->getViEv() == 1) echo 'checked="yes"' ; ?> name="vi_ev" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getViCh() == 1) echo 'checked="yes"' ; ?>  name="vi_ch" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getViSt() == 1) echo 'checked="yes"' ; ?>  name="vi_st" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getViOu() == 1) echo 'checked="yes"' ; ?>  name="vi_ou" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getViEm() == 1) echo 'checked="yes"' ; ?>  name="vi_em" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getViUs() == 1) echo 'checked="yes"' ; ?>  name="vi_us" value="1" type="checkbox"></td>
                        </tr>
                        <tr>
                            <td>Editar</td>
                            <td><input <?php if( $this->data['id_permissao']->getEdCl() == 1) echo 'checked="yes"' ; ?>  name="ed_cl" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getEdEq() == 1) echo 'checked="yes"' ; ?>  name="ed_eq" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getEdCo() == 1) echo 'checked="yes"' ; ?>  name="ed_co" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getEdAr() == 1) echo 'checked="yes"' ; ?>  name="ed_ar" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getEdOp() == 1) echo 'checked="yes"' ; ?>  name="ed_op" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getEdEv() == 1) echo 'checked="yes"' ; ?>  name="ed_ev" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getEdCh() == 1) echo 'checked="yes"' ; ?>  name="ed_ch" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getEdSt() == 1) echo 'checked="yes"' ; ?>  name="ed_st" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getEdOu() == 1) echo 'checked="yes"' ; ?>  name="ed_ou" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getEdEm() == 1) echo 'checked="yes"' ; ?>  name="ed_em" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getEdUs() == 1) echo 'checked="yes"' ; ?>  name="ed_us" value="1" type="checkbox"></td>
                        </tr>
                        <tr>
                            <td>Excluir</td>
                            <td><input <?php if( $this->data['id_permissao']->getExCl() == 1) echo 'checked="yes"' ; ?>  name="ex_cl" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getExEq() == 1) echo 'checked="yes"' ; ?>  name="ex_eq" value="1" type="checkbox"></td>
                            <td><input  <?php if( $this->data['id_permissao']->getExCo() == 1) echo 'checked="yes"' ; ?> name="ex_co" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getExAr() == 1) echo 'checked="yes"' ; ?>  name="ex_ar" value="1" type="checkbox"></td>
                            <td><input  <?php if( $this->data['id_permissao']->getExOp() == 1) echo 'checked="yes"' ; ?> name="ex_op" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getExEv() == 1) echo 'checked="yes"' ; ?>  name="ex_ev" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getExCh() == 1) echo 'checked="yes"' ; ?>  name="ex_ch" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getExSt() == 1) echo 'checked="yes"' ; ?>  name="ex_st" value="1" type="checkbox"></td>
                            <td><input <?php if( $this->data['id_permissao']->getExOu() == 1) echo 'checked="yes"' ; ?>  name="ex_ou" value="1" type="checkbox"></td>
                            <td></td>
                            <td><input <?php if( $this->data['id_permissao']->getExUs() == 1) echo 'checked="yes"' ; ?>  name="ex_us" value="1" type="checkbox"></td>
                        </tr>
                        </tbody>
                    </table>
                </div>





            </div>

            <div class="col-md-4">


            </div>

            <div class="col-md-4">
            </div>

            <div class="col-md-12">

                <input type="submit" class="btn btn-success" value="Salvar">
                <br><br>
            </div>

        </form>

    </div>
</div>

<style type="text/css">
    input, textarea, label{
        display: block;
    }

    .formulario{
        position: relative;
        display: block;
        -webkit-align-content: center;
        -webkit-align-items: center;
        align-self: center;
        width: 100%;
        margin-top: 10px;
        max-width: 500px;
    }
</style>

<script>

    $("#clientes").hide();

    function teste(){
        var x = document.getElementById("cliente").selected;
        console.log(x);
        if(x){
            $("#clientes").show();
            $("#outros").hide();
        }else{
            $("#clientes").hide();
            $("#outros").show();
        }
    }

    $("#gestor").click(function(){
        console.log("click");
    });



</script>
