<?php
?>

<div align="left">
    Você esta em: <a href="<?php echo $this->url('Usuario', array('controller' => 'Usuario', 'action' => 'index')); ?>">Usuarios </a>  > <u>Cadastrar Usuario</u>
</div>
<br>


<div class="tabela col-md-12">
    <div class="tabela-dentro" align="left">
        <h3 class="texto" style="font-size: 18px"> Cadastrar Usuario </h3>
        <?php
        if($this->success)
            echo '<div class="alert alert-success"> '. $this->success[0] .' <button type="button" class="close" data-dismiss="alert"> x </button> </div>';
        if($this->error)
            echo '<div class="alert alert-warning">'. $this->error[0] .' <button type="button" class="close" data-dismiss="alert"> x </button> </div>';

        $this->formElementErrors()
            ->setMessageOpenFormat ('<div class="alert alert-danger"> <button type="button" class="close" data-dismiss="alert"> x </button>')
            ->setMessageCloseString ('</div>');


        ?>

        <form class="" method="post" action="<?php echo $this->url('Usuario', array('controller' => 'Usuario', 'action' => 'inserir')); ?>">
            <div class="col-md-4">
                <div class="form-group">
                    <label >Tipo</label>
                    <select  onclick="teste()" class="form-control" id="tipo" name="tipo">
                        <option value="0"> --Selecione um tipo-- </option>
                        <option value="gestor" id="gestor"> Gestor </option>
                        <option value="vendedor" id="vendedor"> Vendedor </option>
                        <option value="tecnico" id="tecnico"> Técnico </option>
                        <option value="agente" id="agente"> Agente </option>
                        <option value="cliente" id="cliente"> Cliente </option>
                    </select>
                </div>

                <div id="clientes" class="form-group">
                    <label > Clientes</label>
                    <select  class="form-control" name="id_cliente">
                        <option value="0"> --Selecione o cliente -- </option>
                        <?php if ($this->cliente){ ?>
                            <?php foreach($this->cliente as $cliente){ ?>
                                <?php echo '<option value="'.$cliente->getIdCliente().'">  '.$cliente->getNomeFantasia().'</option>'; ?>
                            <?php }} ?>
                    </select>
                </div>
                <div id="outros" class="form-group">
                    <label >Nome</label>
                    <input type="text" class="form-control" name="nome"  placeholder="">
                </div>

                <div  class="form-group">
                    <label >E-mail</label>
                    <input type="email" class="form-control" name="email"  placeholder="">
                </div>


                <div class="form-group">
                    <label > Senha</label>
                    <input type="password" class="form-control" name="senha" placeholder="">
                </div>
                <div class="form-group">
                    <label > Repita a Senha</label>
                    <input type="password" class="form-control" name="senha_2" placeholder="">
                </div>

                <div  class="form-group">
                    <label >Ativo</label>
                    <input type="checkbox"  value="" name="ativo"  placeholder="">
                </div>

                <div id="permissao">
                    <label>Permissões</label>
                    <div id="permissoes">
                        <table class="table table-striped table-condensed table-bordered">
                            <thead>
                                <tr>
                                    <td></td>
                                    <td>Cliente</td>
                                    <td>Equipamento</td>
                                    <td>Contato</td>
                                    <td>Arquivos</td>
                                    <td>Oportunidade</td>
                                    <td>Eventos</td>
                                    <td>Chamados</td>
                                    <td>Status Chamado</td>
                                    <td>Outros Cadastros</td>
                                    <td>Empresas</td>
                                    <td>Usuários</td>
                                </tr>
                            </thead>
                            <tbody align="center">
                                <tr>
                                    <td>Cadastrar</td>
                                    <td><input name="in_cl" value="1" type="checkbox"></td>
                                    <td><input name="in_eq" value="1" type="checkbox"></td>
                                    <td><input name="in_co" value="1" type="checkbox"></td>
                                    <td><input name="in_ar" value="1" type="checkbox"></td>
                                    <td><input name="in_op" value="1" type="checkbox"></td>
                                    <td><input name="in_ev" value="1" type="checkbox"></td>
                                    <td><input name="in_ch" value="1" type="checkbox"></td>
                                    <td><input name="in_st" value="1" type="checkbox"></td>
                                    <td><input name="in_ou" value="1" type="checkbox"></td>
                                    <td><input name="in_em" value="1" type="checkbox"></td>
                                    <td><input name="in_us" value="1" type="checkbox"></td>
                                </tr>
                                <tr>
                                    <td>Visualizar</td>
                                    <td><input name="vi_cl" value="1" type="checkbox"></td>
                                    <td><input name="vi_eq" value="1" type="checkbox"></td>
                                    <td><input name="vi_co" value="1" type="checkbox"></td>
                                    <td><input name="vi_ar" value="1" type="checkbox"></td>
                                    <td><input name="vi_op" value="1" type="checkbox"></td>
                                    <td><input name="vi_ev" value="1" type="checkbox"></td>
                                    <td><input name="vi_ch" value="1" type="checkbox"></td>
                                    <td><input name="vi_st" value="1" type="checkbox"></td>
                                    <td><input name="vi_ou" value="1" type="checkbox"></td>
                                    <td><input name="vi_em" value="1" type="checkbox"></td>
                                    <td><input name="vi_us" value="1" type="checkbox"></td>
                                </tr>
                                <tr>
                                    <td>Editar</td>
                                    <td><input name="ed_cl" value="1" type="checkbox"></td>
                                    <td><input name="ed_eq" value="1" type="checkbox"></td>
                                    <td><input name="ed_co" value="1" type="checkbox"></td>
                                    <td><input name="ed_ar" value="1" type="checkbox"></td>
                                    <td><input name="ed_op" value="1" type="checkbox"></td>
                                    <td><input name="ed_ev" value="1" type="checkbox"></td>
                                    <td><input name="ed_ch" value="1" type="checkbox"></td>
                                    <td><input name="ed_st" value="1" type="checkbox"></td>
                                    <td><input name="ed_ou" value="1" type="checkbox"></td>
                                    <td><input name="ed_em" value="1" type="checkbox"></td>
                                    <td><input name="ed_us" value="1" type="checkbox"></td>
                                </tr>
                                <tr>
                                    <td>Excluir</td>
                                    <td><input name="ex_cl" value="1" type="checkbox"></td>
                                    <td><input name="ex_eq" value="1" type="checkbox"></td>
                                    <td><input name="ex_co" value="1" type="checkbox"></td>
                                    <td><input name="ex_ar" value="1" type="checkbox"></td>
                                    <td><input name="ex_op" value="1" type="checkbox"></td>
                                    <td><input name="ex_ev" value="1" type="checkbox"></td>
                                    <td><input name="ex_ch" value="1" type="checkbox"></td>
                                    <td><input name="ex_st" value="1" type="checkbox"></td>
                                    <td><input name="ex_ou" value="1" type="checkbox"></td>
                                    <td></td>
                                    <td><input name="ex_us" value="1" type="checkbox"></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>


            </div>

            <div class="col-md-4">


            </div>

            <div class="col-md-4">
            </div>

            <div class="col-md-12">

                <input type="submit" class="btn btn-success" value="Salvar">
                <br><br>
            </div>

        </form>

    </div>
</div>

<style type="text/css">
    input, textarea, label{
        display: block;
    }

    .formulario{
        position: relative;
        display: block;
        -webkit-align-content: center;
        -webkit-align-items: center;
        align-self: center;
        width: 100%;
        margin-top: 10px;
        max-width: 500px;
    }
</style>

<script>

    $("#clientes").hide();

    function teste(){
        var x = document.getElementById("cliente").selected;
        var a = document.getElementById("agente").selected;
        console.log(a);
        if(x){
            $("#clientes").show();
            $("#outros").hide();
        }else{
            $("#clientes").hide();
            $("#outros").show();
        }
        if(a){
            $("#permissao").hide();
        }else{
            $("#permissao").show();
        }
    }

    $("#gestor").click(function(){
        console.log("click");
    });



</script>
