<a class="btn btn-info" href="<?php echo $this->url('grupo', array('controller' => 'grupo', 'action' => 'index')); ?>"> Voltar</a>

<h2> Cadastrar Grupo </h2>


<?php
/**
 *
 * @var $form \Zend\Form\Form
 */

    if($this->success)
        echo '<div class="alert alert-success"> '. $this->success[0] .' <button type="button" class="close" data-dismiss="alert"> x </button> </div>';
     if($this->error)
         echo '<div class="alert alert-warning">'. $this->error[0] .' <button type="button" class="close" data-dismiss="alert"> x </button> </div>';

    $this->formElementErrors()
        ->setMessageOpenFormat ('<div class="alert alert-danger"> <button type="button" class="close" data-dismiss="alert"> x </button>')
        ->setMessageCloseString ('</div>');
?>


<div class="formulario">
    <form method="post">

    </form>
</div>

<style type="text/css">
    input, textarea, label{
        display: block;
    }
</style>