<?php

namespace Usuario\Repository;

/**
 * PermissaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissaoRepository extends \Doctrine\ORM\EntityRepository
{


}
